/*
 * data.js — Fonte única de dados das receitas.
 * Cada receita é renderizada na home (index.html) e na página de receita
 * (receita.html) a partir daqui. Para adicionar uma receita, basta acrescentar
 * um objeto neste array — nenhum HTML precisa ser duplicado.
 */

const RECIPES = [
  {
    id: "bolo-de-cenoura",
    title: "Bolo de Cenoura",
    image: "Bolo_de_cenoura.jpg",
    tags: ["Doces", "Bolos", "Favoritos"],
    time: "60 min",
    difficulty: "Fácil",
    servings: 8,
    rating: 4.5,
    description:
      "Um delicioso bolo de cenoura fofinho, coberto com calda de chocolate cremosa. Perfeito para o café da tarde!",
    ingredients: [
      "3 cenouras médias (cerca de 360g) raladas",
      "3 ovos",
      "1 xícara (chá) de óleo de girassol",
      "2 xícaras (chá) de açúcar",
      "2½ xícaras (chá) de farinha de trigo",
      "1 colher (sopa) de fermento em pó",
      "Cobertura: 4 colheres (sopa) de chocolate em pó",
      "Cobertura: 1 xícara (chá) de açúcar",
      "Cobertura: 1 colher (sopa) de manteiga",
      "Cobertura: ½ xícara (chá) de leite",
    ],
    steps: [
      "No liquidificador, bata as cenouras, os ovos e o óleo até ficar homogêneo.",
      "Transfira para uma tigela e adicione o açúcar, misturando bem.",
      "Incorpore a farinha peneirada e, por último, o fermento, mexendo delicadamente.",
      "Despeje em uma forma untada e enfarinhada.",
      "Asse em forno preaquecido a 180°C por cerca de 40 minutos.",
      "Para a cobertura, leve todos os ingredientes ao fogo até engrossar e despeje sobre o bolo ainda morno.",
    ],
    tips: [
      "Faça o teste do palito: se sair limpo, o bolo está pronto.",
      "Não abra o forno nos primeiros 25 minutos para o bolo não solar.",
    ],
  },
  {
    id: "pao-caseiro",
    title: "Pão Caseiro",
    image: "pao.jpg",
    tags: ["Salgadas", "Pães"],
    time: "120 min",
    difficulty: "Fácil",
    servings: 10,
    rating: 5.0,
    description:
      "Pão caseiro macio e saboroso, com casca crocante. Ideal para o café da manhã!",
    ingredients: [
      "1 kg de farinha de trigo",
      "2 colheres (sopa) de fermento biológico seco",
      "2 colheres (sopa) de açúcar",
      "1 colher (sopa) de sal",
      "3 colheres (sopa) de óleo",
      "400 ml de água morna (aproximadamente)",
    ],
    steps: [
      "Em uma tigela, misture a farinha, o açúcar e o sal.",
      "Dissolva o fermento na água morna e adicione à mistura de farinha.",
      "Acrescente o óleo e misture até formar uma massa homogênea.",
      "Sove por cerca de 10 minutos até a massa ficar elástica e lisa.",
      "Deixe descansar por 1 hora, coberta, até dobrar de volume.",
      "Divida a massa, modele os pães e coloque nas formas.",
      "Deixe crescer novamente por 30 minutos.",
      "Asse em forno preaquecido a 180°C por cerca de 40 minutos, até dourar.",
    ],
    tips: [
      "A água deve estar morna, nunca quente, para não matar o fermento.",
      "Um potinho com água no forno deixa a casca mais crocante.",
    ],
  },
  {
    id: "salada-grega",
    title: "Salada Grega",
    image: "Salada_grega.jpg",
    tags: ["Veganas", "Saladas", "Sem Glúten"],
    time: "15 min",
    difficulty: "Fácil",
    servings: 4,
    rating: 4.8,
    description:
      "Salada refrescante com pepino, tomate, azeitonas e temperos mediterrâneos.",
    ingredients: [
      "3 tomates picados",
      "1 pepino em cubos",
      "1 cebola roxa em fatias finas",
      "1 xícara de azeitonas pretas",
      "200g de queijo feta (opcional)",
      "Azeite, orégano, sal e limão a gosto",
    ],
    steps: [
      "Pique todos os vegetais em pedaços médios.",
      "Junte em uma saladeira grande.",
      "Acrescente as azeitonas e o queijo feta em cubos.",
      "Tempere com azeite, orégano, sal e um toque de limão.",
      "Misture delicadamente e sirva gelada.",
    ],
    tips: ["Para versão vegana, omita o queijo feta ou use tofu temperado."],
  },
  {
    id: "lasanha-de-carne",
    title: "Lasanha de Carne",
    image: "Lasanha.jpg",
    tags: ["Salgadas", "Massas", "Favoritos"],
    time: "90 min",
    difficulty: "Médio",
    servings: 6,
    rating: 4.7,
    description:
      "Deliciosa lasanha de carne com camadas de molho e queijo derretido.",
    ingredients: [
      "500g de massa de lasanha",
      "500g de carne moída",
      "2 latas de molho de tomate",
      "300g de presunto",
      "300g de queijo mussarela",
      "1 cebola e 2 dentes de alho picados",
      "Sal, pimenta e manjericão a gosto",
    ],
    steps: [
      "Refogue a cebola e o alho, junte a carne moída e doure.",
      "Adicione o molho de tomate e os temperos; cozinhe por 15 minutos.",
      "Monte em camadas: molho, massa, presunto e mussarela.",
      "Repita as camadas e finalize com molho e queijo por cima.",
      "Asse a 180°C por cerca de 30 minutos, até gratinar.",
    ],
    tips: ["Se usar massa que não precisa pré-cozimento, capriche no molho para hidratá-la."],
  },
  {
    id: "cheesecake-de-morango",
    title: "Cheesecake de Morango",
    image: "cheesecake.jpg",
    tags: ["Doces", "Sobremesas"],
    time: "60 min",
    difficulty: "Médio",
    servings: 8,
    rating: 5.0,
    description:
      "Cheesecake cremoso com cobertura de morangos frescos e geleia.",
    ingredients: [
      "200g de biscoito maisena triturado",
      "100g de manteiga derretida",
      "600g de cream cheese",
      "1 lata de leite condensado",
      "3 ovos",
      "300g de morangos",
      "1 xícara de geleia de morango",
    ],
    steps: [
      "Misture o biscoito com a manteiga e forre o fundo de uma forma.",
      "Bata o cream cheese, o leite condensado e os ovos até homogêneo.",
      "Despeje sobre a base e asse a 160°C por 40 minutos.",
      "Deixe esfriar e leve à geladeira por 4 horas.",
      "Cubra com morangos fatiados e geleia antes de servir.",
    ],
    tips: ["Asse em banho-maria para uma textura ainda mais cremosa."],
  },
  {
    id: "tacos-mexicanos",
    title: "Tacos Mexicanos",
    image: "tacos.jpg",
    tags: ["Salgadas", "Mexicana", "Favoritos"],
    time: "30 min",
    difficulty: "Fácil",
    servings: 4,
    rating: 4.6,
    description:
      "Tacos crocantes recheados com carne temperada, queijo e vegetais frescos.",
    ingredients: [
      "8 tortilhas de milho",
      "400g de carne moída",
      "1 sachê de tempero taco",
      "1 tomate picado",
      "Alface picada",
      "Queijo ralado e guacamole a gosto",
    ],
    steps: [
      "Doure a carne moída com o tempero taco.",
      "Aqueça as tortilhas rapidamente na frigideira.",
      "Recheie com a carne, os vegetais e o queijo.",
      "Finalize com guacamole e sirva imediatamente.",
    ],
    tips: ["Um fio de limão por cima realça todos os sabores."],
  },
  {
    id: "smoothie-verde-detox",
    title: "Smoothie Verde Detox",
    image: "smoothie_verduras.jpg",
    tags: ["Bebidas", "Detox", "Veganas"],
    time: "10 min",
    difficulty: "Fácil",
    servings: 2,
    rating: 4.9,
    description:
      "Bebida refrescante e desintoxicante com folhas verdes, frutas e um toque de gengibre.",
    ingredients: [
      "1 punhado de couve",
      "1 maçã verde",
      "½ pepino",
      "Suco de 1 limão",
      "1 pedaço pequeno de gengibre",
      "200 ml de água de coco",
    ],
    steps: [
      "Lave bem todos os ingredientes.",
      "Bata tudo no liquidificador até ficar homogêneo.",
      "Coe se preferir uma textura mais lisa.",
      "Sirva gelado.",
    ],
    tips: ["Adicione gelo para um resultado mais refrescante."],
  },
  {
    id: "quiche-de-espinafre",
    title: "Quiche de Espinafre e Ricota",
    image: "quiche_espinafre.jpg",
    tags: ["Salgadas", "Vegetariano", "Saudável"],
    time: "50 min",
    difficulty: "Médio",
    servings: 6,
    rating: 4.7,
    description:
      "Uma quiche leve e nutritiva, feita com espinafre fresco e ricota em uma base crocante.",
    ingredients: [
      "1 massa de torta pronta",
      "2 xícaras de espinafre",
      "250g de ricota",
      "3 ovos",
      "200 ml de creme de leite",
      "Sal, noz-moscada e pimenta a gosto",
    ],
    steps: [
      "Forre uma forma com a massa e fure o fundo com um garfo.",
      "Refogue rapidamente o espinafre e reserve.",
      "Bata os ovos com o creme de leite e a ricota.",
      "Junte o espinafre e os temperos ao creme.",
      "Despeje sobre a massa e asse a 180°C por 35 minutos.",
    ],
    tips: ["Deixe descansar 10 minutos antes de fatiar."],
  },
  {
    id: "panquecas-de-banana",
    title: "Panquecas de Banana e Aveia",
    image: "panqueca_banana.jpg",
    tags: ["Doces", "Sem Glúten", "Saudável"],
    time: "20 min",
    difficulty: "Fácil",
    servings: 4,
    rating: 4.8,
    description:
      "Panquecas fofas e sem glúten, feitas com banana e aveia, perfeitas para o café da manhã.",
    ingredients: [
      "2 bananas maduras",
      "2 ovos",
      "1 xícara de aveia em flocos",
      "1 colher (chá) de fermento",
      "1 pitada de canela",
    ],
    steps: [
      "Amasse as bananas e misture com os ovos.",
      "Adicione a aveia, o fermento e a canela.",
      "Deixe a massa descansar por 5 minutos.",
      "Doure pequenas porções em frigideira antiaderente dos dois lados.",
    ],
    tips: ["Sirva com mel, frutas ou pasta de amendoim."],
  },
  {
    id: "brownie-de-chocolate",
    title: "Brownie de Chocolate",
    image: "Brownie.jpg",
    tags: ["Doces", "Bolos", "Sobremesas"],
    time: "45 min",
    difficulty: "Fácil",
    servings: 12,
    rating: 4.8,
    description:
      "Um brownie denso e úmido, com pedaços generosos de chocolate. Perfeito para qualquer ocasião!",
    ingredients: [
      "200g de chocolate meio amargo",
      "150g de manteiga",
      "3 ovos",
      "1 xícara de açúcar",
      "1 xícara de farinha de trigo",
      "100g de nozes ou chocolate em pedaços",
    ],
    steps: [
      "Derreta o chocolate com a manteiga em banho-maria.",
      "Bata os ovos com o açúcar e junte ao chocolate.",
      "Incorpore a farinha delicadamente.",
      "Adicione as nozes e despeje em forma untada.",
      "Asse a 180°C por 25 minutos — o centro deve ficar úmido.",
    ],
    tips: ["Não asse demais: o brownie firma ao esfriar."],
  },
  {
    id: "wrap-de-frango",
    title: "Wrap de Frango com Abacate",
    image: "Wrap.jpg",
    tags: ["Saudável", "Prato Principal", "Low Carb"],
    time: "20 min",
    difficulty: "Fácil",
    servings: 2,
    rating: 4.9,
    description:
      "Um wrap delicioso e nutritivo, recheado com frango grelhado e abacate cremoso.",
    ingredients: [
      "2 tortilhas integrais",
      "1 filé de frango grelhado e desfiado",
      "½ abacate",
      "Folhas de alface",
      "1 tomate em fatias",
      "Iogurte natural e temperos a gosto",
    ],
    steps: [
      "Tempere e grelhe o frango, depois desfie.",
      "Amasse o abacate com sal e limão.",
      "Monte a tortilha com o creme de abacate, o frango e os vegetais.",
      "Enrole firme e corte ao meio.",
    ],
    tips: ["Aqueça a tortilha antes de enrolar para não quebrar."],
  },
  {
    id: "bolinhos-de-halloween",
    title: "Bolinhos Decorados de Halloween",
    image: "Halloween.jpg",
    tags: ["Doces", "Bolos", "Halloween"],
    time: "90 min",
    difficulty: "Médio",
    servings: 10,
    rating: 4.8,
    description:
      "Bolinhos decorados para o Halloween, com sabor de laranja e recheio cremoso. Ótima opção para a festa!",
    ingredients: [
      "3 ovos",
      "2 xícaras de açúcar",
      "2 xícaras de farinha de trigo",
      "1 xícara de suco de laranja",
      "1 colher de fermento",
      "Pasta americana e corantes para decorar",
    ],
    steps: [
      "Bata os ovos com o açúcar até ficar fofo.",
      "Alterne farinha e suco de laranja na massa.",
      "Adicione o fermento por último.",
      "Asse em forminhas a 180°C por 20 minutos.",
      "Depois de frios, decore com pasta americana em temas de Halloween.",
    ],
    tips: ["Use corante em gel para cores mais vibrantes na decoração."],
  },
  {
    id: "smoothie-frutas-vermelhas",
    title: "Smoothie de Frutas Vermelhas",
    image: "Smoothie.jpg",
    tags: ["Bebidas", "Fit", "Café da Manhã"],
    time: "10 min",
    difficulty: "Fácil",
    servings: 2,
    rating: 4.8,
    description:
      "Smoothie cremoso com morango, framboesa, mirtilo, iogurte grego e mel. Rico em antioxidantes!",
    ingredients: [
      "1 xícara de morangos",
      "½ xícara de framboesas",
      "½ xícara de mirtilos",
      "1 pote de iogurte grego",
      "1 colher de mel",
      "Gelo a gosto",
    ],
    steps: [
      "Coloque todas as frutas no liquidificador.",
      "Adicione o iogurte, o mel e o gelo.",
      "Bata até ficar cremoso e sirva imediatamente.",
    ],
    tips: ["Use frutas congeladas para dispensar o gelo."],
  },
  {
    id: "pudim-de-leite",
    title: "Pudim de Leite Condensado",
    image: "Pudim.jpg",
    tags: ["Sobremesas", "Doces"],
    time: "60 min",
    difficulty: "Médio",
    servings: 8,
    rating: 4.9,
    description:
      "Pudim cremoso com calda de caramelo brilhante. Textura aveludada que derrete na boca!",
    ingredients: [
      "1 lata de leite condensado",
      "1 lata de leite (medida da lata)",
      "3 ovos",
      "Calda: 1 xícara de açúcar",
      "Calda: ½ xícara de água",
    ],
    steps: [
      "Faça a calda derretendo o açúcar até dourar, junte a água e caramelize a forma.",
      "Bata no liquidificador o leite condensado, o leite e os ovos.",
      "Despeje na forma caramelizada.",
      "Asse em banho-maria a 180°C por cerca de 1 hora.",
      "Leve à geladeira por 6 horas antes de desenformar.",
    ],
    tips: ["Coe a mistura antes de assar para um pudim sem furinhos."],
  },
  {
    id: "omelete-mediterraneo",
    title: "Omelete Mediterrâneo",
    image: "Omelete.jpg",
    tags: ["Fit", "Café da Manhã", "Low Carb"],
    time: "20 min",
    difficulty: "Fácil",
    servings: 1,
    rating: 4.6,
    description:
      "Omelete fofinho com espinafre, tomate cereja, queijo feta e azeitonas pretas. Rico em proteínas!",
    ingredients: [
      "3 ovos",
      "1 punhado de espinafre",
      "6 tomates cereja",
      "50g de queijo feta",
      "Azeitonas pretas a gosto",
      "Sal, pimenta e azeite",
    ],
    steps: [
      "Bata os ovos com sal e pimenta.",
      "Refogue rapidamente o espinafre e os tomates no azeite.",
      "Despeje os ovos e cozinhe em fogo baixo.",
      "Adicione o feta e as azeitonas, dobre a omelete e sirva.",
    ],
    tips: ["Fogo baixo é o segredo para uma omelete macia."],
  },
  {
    id: "sopa-de-cabotia",
    title: "Sopa Cremosa de Cabotiá",
    image: "SopaCabotia.jpg",
    tags: ["Fit", "Veganas", "Low Carb"],
    time: "35 min",
    difficulty: "Fácil",
    servings: 4,
    rating: 4.9,
    description:
      "Sopa cremosa de cabotiá com leite de coco, curry e gengibre. Reconfortante e saudável!",
    ingredients: [
      "800g de abóbora cabotiá em cubos",
      "1 cebola picada",
      "2 dentes de alho",
      "200 ml de leite de coco",
      "1 colher (chá) de curry",
      "1 pedaço de gengibre",
      "Sal e azeite a gosto",
    ],
    steps: [
      "Refogue a cebola, o alho e o gengibre no azeite.",
      "Junte a abóbora e cubra com água; cozinhe até amaciar.",
      "Bata tudo no liquidificador até ficar cremoso.",
      "Volte à panela, adicione o leite de coco e o curry.",
      "Ajuste o sal e aqueça sem ferver.",
    ],
    tips: ["Finalize com sementes de abóbora tostadas."],
  },
  {
    id: "overnight-oats",
    title: "Overnight Oats com Frutas",
    image: "Overnight.jpg",
    tags: ["Fit", "Café da Manhã", "Vegetariano"],
    time: "10 min (+8h)",
    difficulty: "Fácil",
    servings: 1,
    rating: 4.5,
    description:
      "Aveia preparada com leite vegetal, chia, frutas vermelhas e mel. Prepare à noite e coma pela manhã!",
    ingredients: [
      "½ xícara de aveia em flocos",
      "1 colher de chia",
      "150 ml de leite vegetal",
      "1 colher de mel",
      "Frutas vermelhas a gosto",
    ],
    steps: [
      "Misture a aveia, a chia, o leite e o mel em um pote.",
      "Tampe e leve à geladeira por pelo menos 8 horas.",
      "Pela manhã, finalize com as frutas vermelhas.",
    ],
    tips: ["Dura até 3 dias na geladeira — faça vários potes de uma vez."],
  },
  {
    id: "salmao-assado",
    title: "Salmão Assado com Legumes",
    image: "PeixeAssado.jpg",
    tags: ["Fit", "Prato Principal", "Low Carb"],
    time: "30 min",
    difficulty: "Médio",
    servings: 2,
    rating: 4.9,
    description:
      "Filé de salmão assado com aspargos, brócolis e abobrinha, temperado com ervas frescas e limão.",
    ingredients: [
      "2 filés de salmão",
      "1 maço de aspargos",
      "1 xícara de brócolis",
      "1 abobrinha em rodelas",
      "Suco de 1 limão",
      "Azeite, alho, sal e ervas a gosto",
    ],
    steps: [
      "Tempere o salmão com limão, alho, sal e ervas.",
      "Disponha os legumes em uma assadeira regada com azeite.",
      "Coloque o salmão sobre os legumes.",
      "Asse a 200°C por cerca de 20 minutos.",
    ],
    tips: ["Não asse demais o salmão para ele não ressecar."],
  },
  {
    id: "bowl-de-acai",
    title: "Bowl de Açaí",
    image: "BowlAcai.jpg",
    tags: ["Bebidas", "Fit", "Sobremesas"],
    time: "10 min",
    difficulty: "Fácil",
    servings: 2,
    rating: 4.9,
    description:
      "Açaí cremoso servido na tigela com banana, granola e frutas frescas. Energia pura!",
    ingredients: [
      "400g de polpa de açaí congelada",
      "1 banana",
      "Granola a gosto",
      "Frutas frescas para cobrir",
      "Mel a gosto",
    ],
    steps: [
      "Bata a polpa de açaí com a banana até ficar cremoso.",
      "Sirva em uma tigela.",
      "Cubra com granola, frutas e um fio de mel.",
    ],
    tips: ["Quanto menos líquido, mais cremoso fica o bowl."],
  },
  {
    id: "bolo-de-banana",
    title: "Bolo de Banana",
    image: "bolo_de_banana.jpg",
    tags: ["Doces", "Bolos", "Café da Manhã"],
    time: "50 min",
    difficulty: "Fácil",
    servings: 8,
    rating: 4.7,
    description:
      "Bolo de banana caramelizado por cima, fofinho e aromático. Um clássico da vovó!",
    ingredients: [
      "6 bananas",
      "3 ovos",
      "2 xícaras de farinha de trigo",
      "1 xícara de açúcar",
      "½ xícara de óleo",
      "1 colher de fermento",
      "Canela a gosto",
    ],
    steps: [
      "Bata 3 bananas com os ovos, o açúcar e o óleo.",
      "Junte a farinha e, por último, o fermento.",
      "Forre a forma com as bananas restantes fatiadas e canela.",
      "Despeje a massa e asse a 180°C por 35 minutos.",
    ],
    tips: ["Use bananas bem maduras para mais doçura natural."],
  },
  {
    id: "tapioca-recheada",
    title: "Tapioca Recheada",
    image: "Tapioca.jpg",
    tags: ["Salgadas", "Sem Glúten", "Café da Manhã"],
    time: "15 min",
    difficulty: "Fácil",
    servings: 2,
    rating: 4.6,
    description:
      "Tapioca leve e sem glúten, com recheio de queijo e o que você quiser. Prática e rápida!",
    ingredients: [
      "1 xícara de goma de tapioca hidratada",
      "Queijo coalho ou mussarela",
      "Recheios a gosto (frango, tomate, banana...)",
      "Sal a gosto",
    ],
    steps: [
      "Peneire a goma de tapioca sobre a frigideira quente.",
      "Espalhe formando um disco uniforme.",
      "Quando firmar, adicione o recheio de um lado.",
      "Dobre ao meio e sirva quente.",
    ],
    tips: ["A frigideira antiaderente bem quente é essencial."],
  },
];
